rules:
  description-empty: # Description must not be empty
    level: error
  scope-empty: # Scope must not be empty
    level: warning
  subject-empty: # Subject line should exist
    level: error
  type-empty: # Type must not be empty
    level: error

  type:
    level: error
    options:
      - build
      - chore
      - ci
      - docs
      - feat
      - fix
      - perf
      - refactor
      - revert
      - style
      - test
